<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCk1ag0g\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCk1ag0g/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCk1ag0g.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCk1ag0g\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCk1ag0g\appDevDebugProjectContainer([
    'container.build_hash' => 'Ck1ag0g',
    'container.build_id' => '5809b4bb',
    'container.build_time' => 1737119829,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCk1ag0g');
