<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3ddyngu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3ddyngu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3ddyngu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3ddyngu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3ddyngu\appDevDebugProjectContainer([
    'container.build_hash' => '3ddyngu',
    'container.build_id' => '9d283dc7',
    'container.build_time' => 1736596294,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3ddyngu');
