<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxgoqbd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxgoqbd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAxgoqbd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAxgoqbd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAxgoqbd\appProdProjectContainer([
    'container.build_hash' => 'Axgoqbd',
    'container.build_id' => '0f4881b9',
    'container.build_time' => 1732127718,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxgoqbd');
