<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxhapkb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxhapkb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWxhapkb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWxhapkb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWxhapkb\appProdProjectContainer([
    'container.build_hash' => 'Wxhapkb',
    'container.build_id' => 'e7bcd656',
    'container.build_time' => 1731860626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxhapkb');
